services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - "./:/work"
    working_dir: "/work"
    command: ["air", "-c", ".air.toml"]
    ports:
      - "9000:9000"
  db:
    image: postgres:15.6-bookworm
    ports:
      - "5432:5432"
    volumes:
      - "./.data/postgres:/var/lib/postgresql"
      - "./api/sqlc/schema:/docker-entrypoint-initdb.d"
    command: ["-c", "log_statement=all"]
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "calendar"
