version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@3.1.0

jobs:
  test:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
        name: initialize
        command: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - run:
          name: Download Go modules
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run:
        name: staticcheck
        command: staticcheck ./...
      - run:
          name: Run tests
          command: go test ./...
  deploy-image:
    executor: gcp-cli/default
    steps:
      - setup_remote_docker:
        docker_layer_caching: true
      - gcp-cli/setup:
        version: 459.0.0
      - checkout
      - run:
        name: docker auth
        command: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - run: 
        name: build
        comamnd: make docker-build
      - run: 
        name: push
        command: make docker-push
workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy-image:
          requires:
            - test
