name: ci-buf

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - proto/**
      - .github/workflows/ci-buf.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.26.1"
      - uses: bufbuild/buf-lint-action@v1

