name: ci

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54.2
          skip-pkg-cache: true
      - run: go test ./...

